/**
 * Badge Catalog — Static definitions for all engagement badges.
 *
 * Badges are organized into categories:
 * 1. Learning Milestones — coursework, assignments, CodeLab
 * 2. Streak & Consistency — login streaks, daily engagement
 * 3. Excellence — perfect scores, top grades
 * 4. Level Milestones — reaching specific levels
 * 5. Special / Rare — exploratory, first-day, deep work
 */

export type BadgeCategory =
  | "learning"
  | "streak"
  | "excellence"
  | "level"
  | "special";

export interface BadgeDefinition {
  id: string;               // Unique slug — used as badgeRuleId in DB
  name: string;             // Display name
  description: string;      // What it means
  howToEarn: string;        // Clear, encouraging instruction for students
  category: BadgeCategory;
  /** Lucide icon name (string) */
  iconName: string;
  /** Tailwind text color class for light mode */
  color: string;
  /** Tailwind text color class for dark mode */
  darkColor: string;
  /** Tailwind background color class (low opacity) for the badge pill */
  bgColor: string;
  /** Whether this is a rare/secret badge (shown as ??? until earned) */
  isSecret: boolean;
  /** Minimum level required to even attempt earning this badge (0 = no req) */
  levelRequirement: number;
}

export const BADGE_CATALOG: BadgeDefinition[] = [
  // ─── Learning Milestones ───────────────────────────────────────────────────
  {
    id: "first-submission",
    name: "First Step",
    description: "Submitted your first assignment.",
    howToEarn: "Submit any assignment in any course.",
    category: "learning",
    iconName: "Send",
    color: "text-emerald-600",
    darkColor: "dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab-first",
    name: "Code Curious",
    description: "Completed your first CodeLab level.",
    howToEarn: "Pass any CodeLab level (score ≥ 60%) in any language.",
    category: "learning",
    iconName: "Terminal",
    color: "text-blue-600",
    darkColor: "dark:text-blue-400",
    bgColor: "bg-blue-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab-track-complete",
    name: "Track Champion",
    description: "Completed all 30 levels in any CodeLab language track.",
    howToEarn: "Pass all 30 levels in Python, C++, Java, JavaScript, C#, SQL, HTML, or CSS.",
    category: "learning",
    iconName: "Trophy",
    color: "text-amber-600",
    darkColor: "dark:text-amber-400",
    bgColor: "bg-amber-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab-polyglot",
    name: "Polyglot",
    description: "Completed at least one level in all 8 CodeLab language tracks.",
    howToEarn: "Pass Level 1 in Python, C++, Java, JavaScript, C#, SQL, HTML, AND CSS.",
    category: "learning",
    iconName: "Globe",
    color: "text-violet-600",
    darkColor: "dark:text-violet-400",
    bgColor: "bg-violet-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab-master",
    name: "Code Master",
    description: "Completed all 30 levels in at least 3 CodeLab language tracks.",
    howToEarn: "Fully complete 3 or more language tracks in CodeLab.",
    category: "learning",
    iconName: "Code2",
    color: "text-purple-600",
    darkColor: "dark:text-purple-400",
    bgColor: "bg-purple-500/10",
    isSecret: false,
    levelRequirement: 10,
  },
  {
    id: "assignments-10",
    name: "Dedicated Learner",
    description: "Submitted 10 assignments.",
    howToEarn: "Submit 10 assignments across any courses.",
    category: "learning",
    iconName: "BookCheck",
    color: "text-teal-600",
    darkColor: "dark:text-teal-400",
    bgColor: "bg-teal-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "assignments-50",
    name: "Relentless",
    description: "Submitted 50 assignments.",
    howToEarn: "Submit 50 assignments across any courses.",
    category: "learning",
    iconName: "Layers",
    color: "text-indigo-600",
    darkColor: "dark:text-indigo-400",
    bgColor: "bg-indigo-500/10",
    isSecret: false,
    levelRequirement: 5,
  },
  {
    id: "first-course-enrolled",
    name: "Enrolled",
    description: "Joined your first course.",
    howToEarn: "Get approved into any course.",
    category: "learning",
    iconName: "GraduationCap",
    color: "text-sky-600",
    darkColor: "dark:text-sky-400",
    bgColor: "bg-sky-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "assignment-first",
    name: "First Turn-In",
    description: "Submitted your very first assignment.",
    howToEarn: "Submit any coursework assignment.",
    category: "learning",
    iconName: "BookCheck",
    color: "text-teal-600",
    darkColor: "dark:text-teal-400",
    bgColor: "bg-teal-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "material-first",
    name: "Curious Mind",
    description: "Read your first learning material or syllabus document.",
    howToEarn: "Spend at least 15 seconds reading any course material.",
    category: "learning",
    iconName: "BookOpen",
    color: "text-blue-600",
    darkColor: "dark:text-blue-400",
    bgColor: "bg-blue-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "study-session-first",
    name: "Deep Focus",
    description: "Completed your first 15-minute study focus session.",
    howToEarn: "Complete a Pomodoro study focus session of 15 minutes or longer.",
    category: "learning",
    iconName: "Timer",
    color: "text-purple-600",
    darkColor: "dark:text-purple-400",
    bgColor: "bg-purple-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "discussion-first",
    name: "Active Voice",
    description: "Participated in a course communication or discussion.",
    howToEarn: "Send a meaningful message in course communications.",
    category: "special",
    iconName: "MessageCircle",
    color: "text-indigo-600",
    darkColor: "dark:text-indigo-400",
    bgColor: "bg-indigo-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "flashcard-first",
    name: "Flash of Insight",
    description: "Reviewed a flashcard deck for the first time.",
    howToEarn: "Review any flashcard deck to completion.",
    category: "learning",
    iconName: "Zap",
    color: "text-yellow-600",
    darkColor: "dark:text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "perfect-attendance-week",
    name: "Never Miss a Day",
    description: "Marked present every day in a week.",
    howToEarn: "Be marked as 'Present' for 5 consecutive class sessions.",
    category: "learning",
    iconName: "CalendarCheck",
    color: "text-green-600",
    darkColor: "dark:text-green-400",
    bgColor: "bg-green-500/10",
    isSecret: false,
    levelRequirement: 0,
  },

  // ─── Streak & Consistency ─────────────────────────────────────────────────
  {
    id: "login-streak-3",
    name: "Warming Up",
    description: "Logged in 3 days in a row.",
    howToEarn: "Log in on 3 consecutive days.",
    category: "streak",
    iconName: "Flame",
    color: "text-orange-500",
    darkColor: "dark:text-orange-400",
    bgColor: "bg-orange-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "login-streak-7",
    name: "Week Warrior",
    description: "Logged in 7 days in a row.",
    howToEarn: "Log in for 7 consecutive days without missing a day.",
    category: "streak",
    iconName: "Flame",
    color: "text-orange-600",
    darkColor: "dark:text-orange-400",
    bgColor: "bg-orange-500/15",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "login-streak-14",
    name: "Fortnight Flame",
    description: "Logged in 14 days in a row.",
    howToEarn: "Log in for 14 consecutive days.",
    category: "streak",
    iconName: "Flame",
    color: "text-red-600",
    darkColor: "dark:text-red-400",
    bgColor: "bg-red-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "login-streak-30",
    name: "Monthly Maven",
    description: "Logged in 30 days in a row.",
    howToEarn: "Log in for 30 consecutive days.",
    category: "streak",
    iconName: "Flame",
    color: "text-rose-600",
    darkColor: "dark:text-rose-400",
    bgColor: "bg-rose-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "login-days-100",
    name: "Century Club",
    description: "Logged in 100 unique days total.",
    howToEarn: "Log in on any 100 different days (does not need to be consecutive).",
    category: "streak",
    iconName: "CalendarDays",
    color: "text-purple-600",
    darkColor: "dark:text-purple-400",
    bgColor: "bg-purple-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "early-bird",
    name: "Early Bird",
    description: "Logged in before 7 AM on 5 different days.",
    howToEarn: "Log in before 7:00 AM (your local time) on any 5 days.",
    category: "streak",
    iconName: "Sunrise",
    color: "text-amber-500",
    darkColor: "dark:text-amber-400",
    bgColor: "bg-amber-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "night-owl",
    name: "Night Owl",
    description: "Submitted an assignment after 10 PM on 3 different days.",
    howToEarn: "Submit any assignment after 10:00 PM on 3 separate days.",
    category: "streak",
    iconName: "Moon",
    color: "text-indigo-500",
    darkColor: "dark:text-indigo-400",
    bgColor: "bg-indigo-500/10",
    isSecret: false,
    levelRequirement: 0,
  },

  // ─── Excellence ───────────────────────────────────────────────────────────
  {
    id: "perfect-score",
    name: "Perfectionist",
    description: "Scored 100% on any graded item.",
    howToEarn: "Earn a 100% score on any assignment, quiz, or activity.",
    category: "excellence",
    iconName: "Star",
    color: "text-yellow-500",
    darkColor: "dark:text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "perfect-scores-5",
    name: "Gold Standard",
    description: "Scored 100% on 5 different graded items.",
    howToEarn: "Earn 5 perfect scores across any assignments or activities.",
    category: "excellence",
    iconName: "Award",
    color: "text-amber-500",
    darkColor: "dark:text-amber-400",
    bgColor: "bg-amber-500/10",
    isSecret: false,
    levelRequirement: 3,
  },
  {
    id: "codelab-perfect-level",
    name: "Spotless",
    description: "Scored 100% on a CodeLab level on the first attempt.",
    howToEarn: "Complete any CodeLab level with a perfect score on your very first submission.",
    category: "excellence",
    iconName: "CheckCircle2",
    color: "text-emerald-600",
    darkColor: "dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "grade-honor-roll",
    name: "Honor Roll",
    description: "Maintained an average grade ≥ 90 across all your courses.",
    howToEarn: "Keep your overall grade average at or above 90 in all enrolled courses.",
    category: "excellence",
    iconName: "GraduationCap",
    color: "text-blue-600",
    darkColor: "dark:text-blue-400",
    bgColor: "bg-blue-500/10",
    isSecret: false,
    levelRequirement: 5,
  },

  // ─── Level Milestones ─────────────────────────────────────────────────────
  {
    id: "level-5-bronze",
    name: "Bronze Initiate",
    description: "Reached Level 5 — Bronze Tier.",
    howToEarn: "Accumulate enough EXP to reach Level 5.",
    category: "level",
    iconName: "Shield",
    color: "text-amber-700",
    darkColor: "dark:text-amber-500",
    bgColor: "bg-amber-700/10",
    isSecret: false,
    levelRequirement: 5,
  },
  {
    id: "level-10-silver",
    name: "Silver Ascent",
    description: "Reached Level 10 — Silver Tier.",
    howToEarn: "Accumulate enough EXP to reach Level 10.",
    category: "level",
    iconName: "Shield",
    color: "text-slate-400",
    darkColor: "dark:text-slate-300",
    bgColor: "bg-slate-400/10",
    isSecret: false,
    levelRequirement: 10,
  },
  {
    id: "level-15-gold",
    name: "Gold Seeker",
    description: "Reached Level 15 — Gold Tier.",
    howToEarn: "Accumulate enough EXP to reach Level 15.",
    category: "level",
    iconName: "Shield",
    color: "text-yellow-500",
    darkColor: "dark:text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isSecret: false,
    levelRequirement: 15,
  },
  {
    id: "level-20-platinum",
    name: "Platinum Pioneer",
    description: "Reached Level 20 — Platinum Tier.",
    howToEarn: "Accumulate enough EXP to reach Level 20.",
    category: "level",
    iconName: "Diamond",
    color: "text-cyan-500",
    darkColor: "dark:text-cyan-400",
    bgColor: "bg-cyan-500/10",
    isSecret: false,
    levelRequirement: 20,
  },
  {
    id: "level-25-diamond",
    name: "Diamond Devotee",
    description: "Reached Level 25 — Diamond Tier.",
    howToEarn: "Accumulate enough EXP to reach Level 25.",
    category: "level",
    iconName: "Gem",
    color: "text-blue-400",
    darkColor: "dark:text-blue-300",
    bgColor: "bg-blue-400/10",
    isSecret: false,
    levelRequirement: 25,
  },
  {
    id: "level-30-master",
    name: "Master Mind",
    description: "Reached Level 30 — Master Tier.",
    howToEarn: "Accumulate enough EXP to reach Level 30.",
    category: "level",
    iconName: "Zap",
    color: "text-purple-500",
    darkColor: "dark:text-purple-400",
    bgColor: "bg-purple-500/10",
    isSecret: false,
    levelRequirement: 30,
  },
  {
    id: "level-40-legend",
    name: "Legend",
    description: "Reached Level 40 — Legend Tier. The highest honor.",
    howToEarn: "Accumulate enough EXP to reach Level 40. Reserved for the most dedicated students.",
    category: "level",
    iconName: "Crown",
    color: "text-rose-500",
    darkColor: "dark:text-rose-400",
    bgColor: "bg-rose-500/10",
    isSecret: false,
    levelRequirement: 40,
  },

  // ─── Special / Rare ───────────────────────────────────────────────────────
  {
    id: "first-day",
    name: "Welcome!",
    description: "Logged in for the very first time.",
    howToEarn: "You already have this one — just by being here.",
    category: "special",
    iconName: "PartyPopper",
    color: "text-pink-500",
    darkColor: "dark:text-pink-400",
    bgColor: "bg-pink-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "profile-complete",
    name: "Looking Sharp",
    description: "Filled in all profile fields (name, bio, department, year level).",
    howToEarn: "Complete your full profile in the Profile page.",
    category: "special",
    iconName: "UserCheck",
    color: "text-violet-500",
    darkColor: "dark:text-violet-400",
    bgColor: "bg-violet-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "avatar-uploaded",
    name: "Face of the Future",
    description: "Uploaded a custom profile picture.",
    howToEarn: "Upload a profile picture in your Profile settings.",
    category: "special",
    iconName: "Camera",
    color: "text-sky-500",
    darkColor: "dark:text-sky-400",
    bgColor: "bg-sky-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "deep-work-1h",
    name: "Deep Work Scholar",
    description: "Completed a 1-hour active study session.",
    howToEarn: "Spend 60 continuous minutes actively learning in the LMS.",
    category: "special",
    iconName: "Zap",
    color: "text-emerald-500",
    darkColor: "dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "secret-midnight",
    name: "???",
    description: "A mysterious badge earned at an unusual hour.",
    howToEarn: "Submit something between 12:00 AM and 1:00 AM.",
    category: "special",
    iconName: "Moon",
    color: "text-slate-400",
    darkColor: "dark:text-slate-300",
    bgColor: "bg-slate-500/10",
    isSecret: true,
    levelRequirement: 0,
  },

  // ─── Legacy Activity Badge Aliases ─────────────────────────────────────────
  {
    id: "first_successful_boot",
    name: "First Boot",
    description: "Successfully pass an interactive activity for the first time.",
    howToEarn: "Pass your first interactive activity.",
    category: "learning",
    iconName: "Zap",
    color: "text-emerald-600",
    darkColor: "dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "perfect_score",
    name: "Perfectionist",
    description: "Achieve a 100% score on any activity or assignment.",
    howToEarn: "Earn a perfect 100% score on any activity.",
    category: "excellence",
    iconName: "Trophy",
    color: "text-amber-500",
    darkColor: "dark:text-amber-400",
    bgColor: "bg-amber-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "five_day_streak",
    name: "Consistent Learner",
    description: "Achieve a 5-day activity streak.",
    howToEarn: "Complete activities on 5 consecutive days.",
    category: "streak",
    iconName: "Flame",
    color: "text-orange-500",
    darkColor: "dark:text-orange-400",
    bgColor: "bg-orange-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "python_novice",
    name: "Python Novice",
    description: "Complete a CodeLab activity in Python.",
    howToEarn: "Solve any CodeLab problem using Python.",
    category: "learning",
    iconName: "Terminal",
    color: "text-blue-500",
    darkColor: "dark:text-blue-400",
    bgColor: "bg-blue-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab_first_solve",
    name: "First CodeLab Solve",
    description: "Solve your first CodeLab algorithmic problem with 100% score.",
    howToEarn: "Solve a CodeLab problem with 100% score.",
    category: "learning",
    iconName: "Code2",
    color: "text-emerald-600",
    darkColor: "dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab_hard_solver",
    name: "Hard Problem Master",
    description: "Successfully solve a hard tier CodeLab problem.",
    howToEarn: "Solve any Level 21+ problem in CodeLab.",
    category: "excellence",
    iconName: "Flame",
    color: "text-rose-600",
    darkColor: "dark:text-rose-400",
    bgColor: "bg-rose-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab_champion",
    name: "CodeLab Champion",
    description: "Solve all problems in the CodeLab problem bank.",
    howToEarn: "Pass every problem in CodeLab.",
    category: "excellence",
    iconName: "Crown",
    color: "text-amber-500",
    darkColor: "dark:text-amber-400",
    bgColor: "bg-amber-500/15",
    isSecret: false,
    levelRequirement: 0,
  },
  {
    id: "codelab_streak",
    name: "CodeLab 5-Day Streak",
    description: "Maintain a 5-day active problem solving streak in CodeLab.",
    howToEarn: "Solve CodeLab problems on 5 consecutive days.",
    category: "streak",
    iconName: "Zap",
    color: "text-orange-500",
    darkColor: "dark:text-orange-400",
    bgColor: "bg-orange-500/10",
    isSecret: false,
    levelRequirement: 0,
  },
];

/** Look up a badge definition by its rule ID (handles exact matches and normalized slugs) */
export function getBadgeById(id: string): BadgeDefinition | undefined {
  if (!id) return undefined;
  const direct = BADGE_CATALOG.find((b) => b.id === id);
  if (direct) return direct;

  const normalizedKebab = id.replace(/_/g, "-");
  const kebabMatch = BADGE_CATALOG.find((b) => b.id === normalizedKebab);
  if (kebabMatch) return kebabMatch;

  const normalizedSnake = id.replace(/-/g, "_");
  const snakeMatch = BADGE_CATALOG.find((b) => b.id === normalizedSnake);
  if (snakeMatch) return snakeMatch;

  return undefined;
}

/** Formats a badge rule ID to a clean, human-readable Title Case string if not in catalog */
export function formatBadgeName(id: string): string {
  const def = getBadgeById(id);
  if (def?.name && def.name !== "???") return def.name;
  return id
    .replace(/[_-]/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

/** Get all non-secret badges in a category */
export function getBadgesByCategory(category: BadgeCategory): BadgeDefinition[] {
  return BADGE_CATALOG.filter((b) => b.category === category && !b.isSecret);
}
